development: <%= ENV['REDIS_RESQUE_HOST'] || localhost %>:<%= ENV['REDIS_RESQUE_PORT'] || 6379 %>
test: <%= ENV['REDIS_RESQUE_HOST'] || localhost %>:<%= ENV['REDIS_RESQUE_PORT'] || 6379 %>
production: <%= ENV['REDIS_RESQUE_HOST'] %>:<%= ENV['REDIS_RESQUE_PORT'] %>
